language: ruby

env:
  - DB=cassandra CONFIG_FILE=./config/dolphin-cassandra.conf.travis

rvm:
  - 2.0.0
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

before_install:
  - gem update bundler

before_script:
  - sudo sh -c "echo 'JVM_OPTS=\"\${JVM_OPTS} -Djava.net.preferIPv4Stack=false\"' >> /usr/local/cassandra/conf/cassandra-env.sh"
  - echo "127.0.0.1 " `hostname` | sudo tee /etc/hosts
  - sudo service cassandra start
  - bundle exec ./bin/dolphin_server &

script:
  - bundle exec rake spec

after_script:

branches:
  only:
    - travis-ci-cassandra
