language: ruby

env:
  - DB=mysql CONFIG_FILE=./config/dolphin-mysql.conf.travis

rvm:
  - 1.9.3
  - 2.0.0
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: 1.9.3

before_install:
  - gem update bundler

before_script:
  - mysql -e 'create database dolphin;'
  - bundle exec rake db:mysql:init
  - bundle exec ./bin/dolphin_server &

script:
  - bundle exec rake spec

after_script:
  - bundle exec rake db:mysql:drop

branches:
  only:
    - master
