language: ruby

env:
  - DB=mysql CONFIG_FILE=dolphin-mysql.conf.travis

rvm:
  - 1.9.3

before_install:
  - gem update bundler

before_script:
  - mysql -e 'create database dolphin;'
  - bundle exec rake db:mysql:init
  - bundle exec ./bin/dolphin_server -c "./config/${CONFIG_FILE}" &

script:
  - bundle exec rspec ./spec/files/endpoint/

after_script:
  - bundle exec rake db:mysql:drop

branches:
  only:
    - master
