language: ruby

env:
  - DB=mysql CONFIG_FILE=./config/dolphin-mysql.conf.travis
  - DB=cassandra CONFIG_FILE=./config/dolphin-cassandra.conf.travis

rvm:
  - 2.0.0
  - ruby-head

services:
  - cassandra

matrix:
  allow_failures:
    - rvm: ruby-head

before_install:
  - gem update bundler

before_script:
  - mysql -e 'create database dolphin;'
  - bundle exec rake db:mysql:init
  - bundle exec ./bin/dolphin_server &
  - '/etc/init.d/cassandra status'
  - /usr/bin/cassandra-cli -h 127.0.0.1 -k ./config/db/cassandra_schema.txt
  - sleep 5

script:
  - bundle exec rake spec

after_script:
  - bundle exec rake db:mysql:drop

branches:
  only:
    - master
    - fix-0.0.5
    - travis-ci-cassandra
