language: ruby

env:
  - DB=cassandra CONFIG_FILE=./config/dolphin-cassandra.conf.travis

rvm:
  - 2.0.0
  - ruby-head

services:
  - cassandra

matrix:
  allow_failures:
    - rvm: ruby-head

before_install:
  - gem update bundler

before_script:
  - sleep 10
  - bundle exec ./bin/dolphin_server &

script:
  - bundle exec rake spec

after_script:

branches:
  only:
    - travis-ci-cassandra
